### ISSUE TITLE
Lazy command loader

### ISSUE THREAD

**Issue by geerteltink** [laminas/laminas-cli#11]
### Feature Request

Would there be interest in a lazy command loader? The downside of Symfony cli is that all commands need to be started, including all dependencies. Some may take a longer time to load. When there are a lot of commands this might slow down the cli before it shows anything. Or causes errors because a service is not ready yet.

By wrapping commands in a lazy command loader, only the command that runs is started. To get the overview, the needed data is extracted without initializing the command.

A working example can be found here: https://github.com/xtreamwayz/expressive-console/blob/master/src/LazyLoadingCommand.php

**Comment by froschdesign** [comment]
@geerteltink 
Please look at #2 - "Lazy loading commands"

**Comment by michalbundyra** [comment]
@geerteltink thanks, already implemented. See #7.

**Comment by geerteltink** [comment]
That is lazy loading if you execute 1 specific command. What if you run `vendor/bin/laminas`? It still loads and starts all commands to get the descriptions of all commands.

**Comment by weierophinney** [comment]
@michalbundyra I'm re-opening, because @geerteltink is correct. Right now, the symfony/console application still has to pull each command instance from the container in order to run `configure()` and build the description strings for each command. Geert has previously figured out a way to get that information via reflection, which is what he linked you to.
