### ISSUE TITLE
Issue with integrating symfony/messenger command

### ISSUE THREAD

**Issue by tworzenieweb** [laminas/laminas-cli#28]
### Bug Report

The whole console application might fail completely when an exception is thrown in lazy command configure a part

|    Q        |   A
|------------ | ------
| Version(s)  | dev-master

#### Summary

It looks like the LazyLoadingCommand is having a part that might sometimes throw an exception because of not initialized dependencies of the underlying command.

For example:

```
    /**
     * {@inheritdoc}
     */
    protected function configure(): void
    {
        $defaultReceiverName = 1 === \count($this->receiverNames) ? current($this->receiverNames) : null;

        $this
            ->setDefinition([
                new InputArgument('receivers', InputArgument::IS_ARRAY, 'Names of the receivers/transports to consume in order of priority', $defaultReceiverName ? [$defaultReceiverName] : []),
                new InputOption('limit', 'l', InputOption::VALUE_REQUIRED, 'Limit the number of received messages'),
                new InputOption('memory-limit', 'm', InputOption::VALUE_REQUIRED, 'The memory limit the worker can consume'),
                new InputOption('time-limit', 't', InputOption::VALUE_REQUIRED, 'The time limit in seconds the worker can run'),
                new InputOption('sleep', null, InputOption::VALUE_REQUIRED, 'Seconds to sleep before asking for new messages after no messages were found', 1),
                new InputOption('bus', 'b', InputOption::VALUE_REQUIRED, 'Name of the bus to which received messages should be dispatched (if not passed, bus is determined automatically)'),
            ])
// the rest of the code
}
```

As a solution, we could catch any incoming errors being thrown by the configure method, because it might be a common scenario that some configuration steps are based on internal dependencies injected.

```
        // \Laminas\Cli\LazyLoadingCommand
        try{
            $command->configure();
        } catch (\Throwable $exception) {}
```

#### Current behavior

This code is throwing a warning exception because of empty receiverNames property, then the whole list is not displaying

#### How to reproduce

Connect Symfony messenger consume command to the app and run the CLI

#### Expected behavior

No error should be thrown and the list of available commands should be displayed.

**Comment by michalbundyra** [comment]
@tworzenieweb thanks for reporting the issue.

We kinda know about it. This is the limitation of lazy loading here.
We might consider wrapping it with try...catch and skip lazy loading in case of errors.
BTW not sure if it is the best approach to use dependencies in configure.

**Comment by tworzenieweb** [comment]
Yes, I agree, I think having try-catch wrapping, as we both mentioned makes a lot of sense. Also maybe within symfony/messenger they can fix it by providing empty array default which is not the case right now

**Comment by geerteltink** [comment]
> Was the rationale for lazy loading was to prevent expensive operations when doing operations like list and help? Or were there other scenarios you were addressing? I'm beginning to think that we should just make a prominent note in the documentation that users should not perform expensive operations in the constructor or configure().

The whole reason I had it for my own cli is that Symfony cli loads all dependencies if you list the commands. If you have some expensive dependencies it takes a while which can be annoying at times. Besides that in a few projects I loaded dev commands, commands to initialize and setup a project, generate keys etc. Some things where done when the database or other services were not available. I ended up writing bash scripts first and then came up with this solution.

One of the solutions could be to use the proxy-manager to prevent loading those dependencies. I have seen multiple requests and attempts to change this Symfony cli behavior without any success. The easiest solution would be to make the command config function but I doubt that is ever going to happen.

So, do we need it this lazy command loading? Not really. Is it nice to have? That's for sure. The only way to implement it without issues is to catch somehow exceptions and leave description empty if the command fails. The exception mentioned by @tworzenieweb  is exactly the same one I encountered as well. It's caused by the symfony messenger package. Another solution is to send a patch for that package so it doesn't try to execute non static related code.

When you link that symfony messenger command it doesn't throw an exception though, It triggers a warning:

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in .../vendor/symfony/messenger/Command/ConsumeMessagesCommand.php on line 61
```

A working fix for the issue is this:

```
        // src/LazyLoadingCommand.php
        /** @var Command $command */
        $command = (new ReflectionClass($commandClass))->newInstanceWithoutConstructor();
        $command->setDefinition(new InputDefinition());
        $command->setName($name);

        try {
            $command->configure();
            $this->setDefinition($command->getDefinition());
            $this->setDescription($command->getDescription());
            $this->setHelp($command->getHelp());
        } catch (Throwable $e) {
        }
```

**Comment by weierophinney** [comment]
> When you link that symfony messenger command it doesn't throw an exception though, It triggers a warning, maybe we can silence it:
> 
> ```
> PHP Warning:  count(): Parameter must be an array or an object that implements Countable in
> ```

Right - this is why I asked the OP if they had an error handler in place.

My take on this is that if there are commands with heavy dependencies that impact performance of `list` and `help`, they likely need to be rewritten, or pushed into a wrapper of some sort.

I think the reason that Symfony hasn't changed the behavior is because there are legitimate cases where _required constructor arguments_ are used to help generate _command metadata_, such as options, default values, etc.; it's precisely what's happening in the command demonstrating the issue. And if that's the case, a proxy class is going to make consuming the command harder, as it's now possible that information that would normally be populated is now missing.

As such, I think for now, we should remove the feature, as it's raising more issues than it solves (as **all** commands are now lazy loaded, which can lead to these problems).

If we get reports of issues, I think we can document how you might decorate such commands, which would likely require a combination of running `list` and `help` without decoration, and then using that information to create a proxy command. If we have to, we could even potentially provide a delegator factory for doing this.
