### ISSUE TITLE
Replace ocramius/package-versions with composer/package-versions-deprecated

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-cli#35]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

To support Composer 2 for all of the laminas packages, we have to replace `ocramius/package-versions` with composers fork `composer/package-versions-deprecated`.
The fork removed the PHP 7.4 limitation and thus provides Composer 2 support for PHP <7.4.

[composer/package-versions-deprecated](https://github.com/composer/package-versions-deprecated) is replacing `ocramius/package-versions` and thus can be used as a 1:1 replacement.

**Comment by Ocramius** [comment]
You can also keep the dependencies as they are, and you get out of the box composer 2 support if you run with PHP 7.4+

**Comment by boesing** [comment]
Yes I know, but actually, we decided in the TSC that all laminas packages should support current PHP versions (which includes PHP 7.3 until december this year). Thus, we have to switch dependencies here. 🤷‍♂️

**Comment by weierophinney** [comment]
I'm a bit confused.

In reading the README on composer/package-versions-deprecated... it's a 1:1 of ocramius/package-versions. No changes. No additional class aliases. Meanwhile, ocramius/package-versions still works, and can work against each version of PHP that laminas-cli supports. How will it stop working with Composer 2, exactly? That's not spelled out anywhere, which is why I'm wondering what the need is for the Composer-maintained package. If that package did some class aliasing or similar so that we could use the class names as presented in Composer 2, it would be a no-brainer for me, but right now, I'm just scratching my head...

**Comment by Ocramius** [comment]
> Thus, we have to switch dependencies here. 🤷‍♂️

You can pin to an older `ocramius/package-versions`.

Should somebody need to run PHP 7.1 and composer v2, adding `composer/package-versions-deprecated` (note: not replacing) already does the trick for them.

**Comment by boesing** [comment]
@weierophinney `ocramius/package-versions` only supports composer v2 if you are on PHP 7.4+
AFAIR, laminas packages are supporting *all* actively supported PHP Versions (which is PHP 7.3+ until december 2020).

As @Ocramius states, every user is free to require `composer/package-versions-deprecated` themselves. As this requires additional steps for many users, I prefer switching the package.

There are packages available which still support PHP 5.6 afaik.

So we can choose from 3 solutions:
- dont change anything and let users require `composer/package-versions-deprecated` which they might not be aware of
- create an additional PR and require PHP 7.4 as minimum version and target next minor where we are free to raise PHP versions?
- migrate to `composer/package-versions-deprecated`

I dont really have a preferred solution - I just want to keep the migration path for users as smooth as possible.

**Comment by weierophinney** [comment]
@boesing Okay, that gives me the context I needed - thanks!
