### ISSUE TITLE
Disable xdebug extension before executing any command

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-cli#40]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I am using `laminas-cli` to parse some files with `nikic/php-parser` and ran into xdebug errors due to reaching the maximum nesting level which is per-default `256`.
As a quickfix, I'd run `laminas-cli` with `php -n` to avoid loading *any* extension, but I dont really want to use this in the commands description.

There are libs like `composer/xdebug-handler` which are [used by composer](https://github.com/composer/composer/blob/f7f7883a5ed62b3e0a26533e3afb3730fdfa54d8/bin/composer#L17) aswell.

I'd like to propose this library to be implemented in `laminas-cli` directly.

**Comment by Ocramius** [comment]
I don't think the library should mess with the execution environment at all

**Comment by geerteltink** [comment]
I agree, xdebug shouldn't be disabled by this component. Can't you configure xdebug in such way that it doesn't start automatically from cli, only when setting a env var?

**Comment by boesing** [comment]
If xdebug extension is added to `php.ini`, there is no way to remove it in runtime or enable/disable it with an environment variable. 
It makes a huge difference in performance when executing a command with `nikic/php-parser`.

However, there is a reason why `composer` added it to its binary. I can change the `xdebug.max_nesting_level` ini setting in my command but that will still keep xdebug enabled and thus the command consuming more CPU and memory than it should.

I know, there were performance improvements in xdebug lately, so "probably" this wont be an issue in the future.

I know that messing with executing environment is not recommended, but I dont see a better way in having this problem solved. 🤷‍♂️

**Comment by boesing** [comment]
Psalm uses the composer xdebug handler aswell (and extending it with some own stuff).

https://github.com/vimeo/psalm/blob/master/src/psalm.php#L425
https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Fork/PsalmRestarter.php

**Comment by weierophinney** [comment]
@Ocramius and @geerteltink —

I didn't understand what the reference to composer/xdebug-handler was about, and so decided to look into the package.

Essentially, it grabs the current INI configuration, determines if XDebug is enabled, and, if so, toggles it off and dumps the INI to a temp file, which it then passes to the PHP executable in order to re-run its process.

There's one more bit to it, though: you can **use an env variable to keep XDebug enabled** if desired (generally named `{your app}_ALLOW_XDEBUG`).

The majority of what laminas-cli targets will not benefit from XDebug, so having it disabled by default makes a ton of sense. But if you _do_ want it, I like the idea of being able to use an env variable, as that's easily scriptable (e.g., in `composer.json`, you could do a script as follows: `LAMINAS_ALLOW_XDEBUG=1 laminas some:command`).

This approach gives us both the performance benefits, _and_ the ability to use XDebug when desired. As such, I'm :+1:.

**Comment by weierophinney** [comment]
So, based on:

- The issue (xdebug/xdebug#623) that  @Ocramius has opened against the v2 branch of Xdebug, and
- The fact these issues are essentially mitigated in the upcoming Xdebug v3,

I think we should close this issue, as it will be resolved elsewhere. In the meantime, you can create a wrapper for the laminas binary that disables affected INI settings:

```bash
php -d xdebug.max_nesting_level=-1 vendor/bin/laminas "$@"
```

(or create a command that proxies to `vendor/bin/laminas` by first using the composer/xdebug-handler functionality)

**Comment by Ocramius** [comment]
Careful! I only opened this against the 3.x branch of Xdebug (for now)!
