### ISSUE TITLE
Usage in non-laminas projects - custom container provider

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-cli#63]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

I'd like to have a way to provide a container without having to create `config/container.php` or `config/application.config.php`.

When developing commands in a library, I'd like to have some kind of "integration" validation. 
Like: 
- is the command detected from the laminas CLI command
- how does my description look like when executing CLI command with `--help`
- e.g.

For now, I can create `config/container.php` or `config/application.config.php` and we're good to go. But I wonder if its possible to either add an option to a file where the container can be found or handle it like doctrine does with its `cli-config.php`.

I'd like to get some more ideas about this.

**Comment by weierophinney** [comment]
If you look at how `bin/laminas` is written, it literally seeds the factory for producing the console application by calling `ContainerResolver::resolve()`. What we currently do is:

- If `config/container.php` exists, we use it.
- If `config/application.config.php` exists, we bootstrap the Laminas-MVC application's module manager in order to produce the container.

As such, we can update this class to add additional mechanisms for producing a container. What I'm wondering is: how is your problem NOT solved by dropping in a `config/container.php` file into your application? What would solve it better?

**Comment by boesing** [comment]
In a project which does not follow laminas directory conventions, I'd rather not create a directory `config` just to provide  `config/container.php`.

I think, we could support something like `container.php` in the project root aswell.
